import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'

export default function Home() {

  React.useEffect(() => {
	  console.log("--------------------")
    window.API = {
      LMSInitialize: () => {
        console.log("-----------------LMSInitialize------------------")
      },
      LMSGetValue: () => {
        console.log("-----------------LMSGetValue------------------")
      },
      LMSSetValue: () => {
        console.log("-----------------LMSSetValue------------------")
      },
      LMSGetLastError: () => {
        console.log("-----------------LMSGetLastError------------------")
      },
      LMSGetErrorString: () => {
        console.log("-----------------LMSGetLastError------------------")
      },
      LMSGetDiagnostic: () => {
        console.log("-----------------LMSGetDiagnostic------------------")
      },
      LMSCommit: () => {
        console.log("-----------------LMSCommit------------------")
      },
      LMSFinish: () => {
        console.log("-----------------LMSFinish------------------")
      },
    }

    window.API_1484_11 = {
      Initialize: () => {
        console.log("-----------------Initialize------------------")
      },
      Terminate: () => {
        console.log("-----------------Terminate------------------")
      },
      GetValue: () => {
        console.log("-----------------GetValue------------------")
      },
      SetValue: () => {
        console.log("-----------------SetValue------------------")
      },
      Commit: () => {
        console.log("-----------------Commit------------------")
      },
      GetLastError: () => {
        console.log("-----------------GetLastError------------------")
      },
      GetErrorString: () => {
        console.log("-----------------GetErrorString------------------")
      },
      GetDiagnostic: () => {
        console.log("-----------------GetDiagnostic------------------")
      }
    }
    
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Scorm appsd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <iframe src={`https://scorm.raji.yoga/scorm/index_lms.html`} style={{height: '1000px', width: '1000px'}}>
        </iframe>
    </div>
  )
}